name: publish DEV to dockerhub

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: publish DEV to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build (and publish) docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            fopina/go-mijia:dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=dev
